---
# download and extract pseudopotentials
- name: download "{{ pp.file }}"
  get_url:
    url: "{{ pp.url }}/{{ pp.file }}"
    dest: "{{ quantum_espresso_code_folder }}/{{ pp.file }}"
    mode: "u+r"
  register: pp_download

- name: "Create {{ pp.folder }}/"
  become: true
  file:
    path: "{{ quantum_espresso_data_folder }}/{{ pp.folder }}"
    state: directory

- name: "Unpack {{ pp.file }}"
  become: true
  unarchive:
    src: "{{ pp_download.dest }}"
    dest: "{{ quantum_espresso_data_folder }}/{{ pp.folder }}"
    remote_src: true
  register: pp_extract
